// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor.Data;

namespace Servidor.Migrations
{
    [DbContext(typeof(EuroMilhoesContext))]
    [Migration("20210611144544_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Servidor.Models.ApostasArquivada", b =>
                {
                    b.Property<int>("Nif")
                        .HasColumnType("int")
                        .HasColumnName("nif");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("datetime");

                    b.Property<string>("Estrelas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estrelas");

                    b.Property<string>("Numeros")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeros");

                    b.HasKey("Nif", "DataAposta")
                        .HasName("PK__ApostasA__839469AF50F0464C");

                    b.ToTable("ApostasArquivadas");
                });

            modelBuilder.Entity("Servidor.Models.ApostasAtuai", b =>
                {
                    b.Property<int>("Nif")
                        .HasColumnType("int")
                        .HasColumnName("nif");

                    b.Property<DateTime>("DataAposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Estrelas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estrelas");

                    b.Property<string>("Numeros")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeros");

                    b.Property<bool?>("SorteioAtual")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Nif", "DataAposta")
                        .HasName("PK__ApostasA__839469AF90EABA56");

                    b.ToTable("ApostasAtuais");
                });
#pragma warning restore 612, 618
        }
    }
}
